language: node_js
os:
- linux
node_js:
- '6'
- '5'
- '4'
before_script:
- npm install -g gulp
script: npm test
after_success:
- npm run coverage
compiler:
  - g++
env:
- CXX=g++-4.8
sudo: false
services:
  - couchdb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  slack:
    secure: XpTm299CGOLlxcCd4qO0vF6ba58oAcwgANPTN5q1KeB7K65Hp9g2G8Vnu6KhVOOcNiN3FP5AaVt4Qb80lYdSRjKqmlGtTUAFw/2aPoYgx3cZ+HA/gu+q92USigrjwz3cMWuNOR/I2uYp1KW947mBRZl0S+MvGvgL4wqXVjHTcmE=